---
title: "NCHS_ResearchProj_MAPS_BakerSunderland"
author: "Sunderland Baker"
date: '2022-07-12'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=TRUE}
library(haven)
library(dplyr)
library(tidyverse)
#Uploading data from OneDrive repository.
screener_2018 <- read_sas("C:/Users/Sunderland Baker/OneDrive - Colorado College/JUNIOR YEAR/BIOS6670/NCHS Research Project/nsch_2018_screener.sas7bdat")
topical_2018 <- read_sas("C:/Users/Sunderland Baker/OneDrive - Colorado College/JUNIOR YEAR/BIOS6670/NCHS Research Project/nsch_2018_topical.sas7bdat")
screener_2019 <- read_sas("C:/Users/Sunderland Baker/OneDrive - Colorado College/JUNIOR YEAR/BIOS6670/NCHS Research Project/nsch_2019_screener.sas7bdat")
topical_2019 <- read_sas("C:/Users/Sunderland Baker/OneDrive - Colorado College/JUNIOR YEAR/BIOS6670/NCHS Research Project/nsch_2019_topical.sas7bdat")
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Organizing it into just the main variables that will be used for mapping.
t_2018 <- topical_2018 %>% select(YEAR, FIPSST, SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, K2Q32A, K2Q33A, ACE1, ACE3, ACE4, ACE5, ACE6, ACE7, ACE8, ACE9, ACE10)
t_2019 <- topical_2019 %>% select(YEAR, FIPSST, SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, K2Q32A, K2Q33A, ACE1, ACE3, ACE4, ACE5, ACE6, ACE7, ACE8, ACE9, ACE10)
dta <- rbind(t_2018, t_2018)

#Limiting the age range per our discussions
DataOff <- dta %>% filter(dta$SC_AGE_YEARS>=13 & dta$SC_AGE_YEARS<=18)

#just yielding complete cases for mapping to avoid NA
DO_1 <- DataOff[complete.cases(DataOff[ , c("SC_AGE_YEARS","SC_HISPANIC_R", "SC_RACE_R", "SC_SEX", "BMICLASS", "PHYSACTIV", "SCREENTIME", "HOURSLEEP", "K2Q33A", "K2Q32A","ACE1","ACE3","ACE4","ACE5","ACE6","ACE7","ACE8","ACE9","ACE10")]), ] 
dim(DO_1) #checking the dimensions of official data frame
DO_1$BMICLASS2 <- ifelse(DO_1$BMICLASS %in% c(1,2), 1, ifelse(
  DO_1$BMICLASS==3, 2, 3))
```

```{r, echo=TRUE}
#US Map Plots 
library(usmap)
library(ggplot2)
library(openintro)
library(readxl)
library(statsr)
library(rio)
library(skimr)
library(broom)
library(RColorBrewer)
library(scales)
library(dplyr)
DO_1a <- dplyr::rename(DO_1, fips = FIPSST)
#Variable recategorization for optimal RF output
DO_1a$BMICLASS2 <- factor(as.integer(DO_1a$BMICLASS2), levels = c(1,2,3), labels = c("0-5th perc","5-95th perc", "95-100th perc"))

DO_1a$SC_RACE_R <- factor(as.integer(DO_1a$SC_RACE_R), levels = c(1,2,3,4,5,7), labels = c("White","Black or African American","American Indian or Alaska Native","Asian","Native Hawaiian or Pacific Islander","Two or More Races"))

DO_1a$OVERWEIGHT <- factor(as.integer(DO_1a$OVERWEIGHT), levels = c(1,2), labels = c("Yes","No"))

DO_1a$PHYSACTIV <- factor(as.integer(DO_1a$PHYSACTIV), levels = c(1,2,3,4), labels = c("0 days","1-3 days","4-6 days","Every day"))

DO_1a$ACE1_temp <- ifelse(DO_1a$ACE1 %in% c(3,4), 1, 0)
DO_1a$ACE_Count <- rowSums(DO_1a[,c("ACE1_temp", paste0("ACE", c(3:10)))], na.rm = T)

-------------------#MAP MAKING#--------------------------
#MAP 1: BMICLASS2 Geospatial Visualization
colORs <- brewer.pal(3,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = DO_1a, values = "BMICLASS2") + scale_fill_manual(values = colORsp(3)) + labs(title = "BMI Classification of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "BMI Class of Children") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))



#MAP 2: OVERWEIGHT Geospatial Visualization
colORs <- brewer.pal(2,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = DO_1a, values = "OVERWEIGHT") + scale_fill_manual(values = colORsp(2)) + labs(title = "Overweight Classification of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "Overweight Classification") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))

#MAP 3: RACE Geospatial Visualization
colORs <- brewer.pal(6,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = DO_1a, values = "SC_RACE_R") + scale_fill_manual(values = colORsp(6)) + labs(title = "Racial Categories of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "Racial Category") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))

#MAP 4: PHYSACTIV Geospatial Visualization
colORs <- brewer.pal(4,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = DO_1a, values = "PHYSACTIV") + scale_fill_manual(values = colORsp(4)) + labs(title = "Physical Activity Frequency of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "PA Levels in Children") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))

#MAP 5: ACE AGGREGATE Geospatial Visualization
DO_1a$ACE_Count <- factor(as.integer(DO_1a$ACE_Count), levels = c(0,1,2,3,4,5,6,7,8,9), labels = c(0,1,2,3,4,5,6,7,8,9))
colORs <- brewer.pal(10,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = DO_1a, values = "ACE_Count") + scale_fill_manual(values = colORsp(10)) + labs(title = "ACE Counts of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "ACE Count of Children") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))

```

## Remaking the Maps to investigate if averages are being taken per state.
```{r, echo=TRUE}
#MAP 1: BMICLASS2---------------------------------------
#Averaging out variables for mapping before factorizing.
DO_1a <- dplyr::rename(DO_1, fips = FIPSST)

#Variable recategorization for optimal RF output
bmi_al <- DO_1a %>%
  filter(fips == "01")
al <- round(mean(bmi_al$BMICLASS2))
bmi_ak <- DO_1a %>%
  filter(fips == "02")
ak <- round(mean(bmi_ak$BMICLASS2))
bmi_az <- DO_1a %>%
  filter(fips == "04")
az <- round(mean(bmi_az$BMICLASS2))
bmi_ar <- DO_1a %>%
  filter(fips == "05")
ar <- round(mean(bmi_ar$BMICLASS2))
bmi_ca <- DO_1a %>%
  filter(fips == "06")
ca <- round(mean(bmi_ca$BMICLASS2))
bmi_co <- DO_1a %>%
  filter(fips == "08")
co <- round(mean(bmi_co$BMICLASS2))
bmi_ct <- DO_1a %>%
  filter(fips == "09")
ct <- round(mean(bmi_ct$BMICLASS2))
bmi_de <- DO_1a %>%
  filter(fips == "10")
de <- round(mean(bmi_de$BMICLASS2))
bmi_fl <- DO_1a %>%
  filter(fips == "12")
fl <- round(mean(bmi_fl$BMICLASS2))
bmi_ga <- DO_1a %>%
  filter(fips == "13")
ga <- round(mean(bmi_ga$BMICLASS2))
bmi_hi <- DO_1a %>%
  filter(fips == "15")
hi <- round(mean(bmi_hi$BMICLASS2))
bmi_id <- DO_1a %>%
  filter(fips == "16")
id <- round(mean(bmi_id$BMICLASS2))
bmi_il <- DO_1a %>%
  filter(fips == "17")
il <- round(mean(bmi_il$BMICLASS2))
bmi_in <- DO_1a %>%
  filter(fips == "18")
IN <- round(mean(bmi_in$BMICLASS2))
bmi_ia <- DO_1a %>%
  filter(fips == "19")
ia <- round(mean(bmi_ia$BMICLASS2))
bmi_ks <- DO_1a %>%
  filter(fips == "20")
ks <- round(mean(bmi_ks$BMICLASS2))
bmi_ky <- DO_1a %>%
  filter(fips == "21")
ky <- round(mean(bmi_ky$BMICLASS2))
bmi_la <- DO_1a %>%
  filter(fips == "22")
la <- round(mean(bmi_la$BMICLASS2))
bmi_me <- DO_1a %>%
  filter(fips == "23")
me <- round(mean(bmi_me$BMICLASS2))
bmi_md <- DO_1a %>%
  filter(fips == "24")
md <- round(mean(bmi_md$BMICLASS2))
bmi_ma <- DO_1a %>%
  filter(fips == "25")
ma <- round(mean(bmi_ma$BMICLASS2))
bmi_mi <- DO_1a %>%
  filter(fips == "26")
mi <- round(mean(bmi_mi$BMICLASS2))
bmi_mn <- DO_1a %>%
  filter(fips == "27")
mn <- round(mean(bmi_mn$BMICLASS2))
bmi_ms <- DO_1a %>%
  filter(fips == "28")
ms <- round(mean(bmi_ms$BMICLASS2))
bmi_mo <- DO_1a %>%
  filter(fips == "29")
mo <- round(mean(bmi_mo$BMICLASS2))
bmi_mt <- DO_1a %>%
  filter(fips == "30")
mt <- round(mean(bmi_mt$BMICLASS2))
bmi_ne <- DO_1a %>%
  filter(fips == "31")
ne <- round(mean(bmi_ne$BMICLASS2))
bmi_nv <- DO_1a %>%
  filter(fips == "32")
nv <- round(mean(bmi_nv$BMICLASS2))
bmi_nh <- DO_1a %>%
  filter(fips == "33")
nh <- round(mean(bmi_nh$BMICLASS2))
bmi_nj <- DO_1a %>%
  filter(fips == "34")
nj <- round(mean(bmi_nj$BMICLASS2))
bmi_nm <- DO_1a %>%
  filter(fips == "35")
nm <- round(mean(bmi_nm$BMICLASS2))
bmi_ny <- DO_1a %>%
  filter(fips == "36")
ny <- round(mean(bmi_ny$BMICLASS2))
bmi_nc <- DO_1a %>%
  filter(fips == "37")
nc <- round(mean(bmi_nc$BMICLASS2))
bmi_nd <- DO_1a %>%
  filter(fips == "38")
nd <- round(mean(bmi_nd$BMICLASS2))
bmi_oh <- DO_1a %>%
  filter(fips == "39")
oh <- round(mean(bmi_oh$BMICLASS2))
bmi_ok <- DO_1a %>%
  filter(fips == "40")
ok <- round(mean(bmi_ok$BMICLASS2))
bmi_or <- DO_1a %>%
  filter(fips == "41")
or <- round(mean(bmi_or$BMICLASS2))
bmi_pa <- DO_1a %>%
  filter(fips == "42")
pa <- round(mean(bmi_pa$BMICLASS2))
bmi_ri <- DO_1a %>%
  filter(fips == "44")
ri <- round(mean(bmi_ri$BMICLASS2))
bmi_sc <- DO_1a %>%
  filter(fips == "45")
sc <- round(mean(bmi_sc$BMICLASS2))
bmi_sd <- DO_1a %>%
  filter(fips == "46")
sd <- round(mean(bmi_sd$BMICLASS2))
bmi_te <- DO_1a %>%
  filter(fips == "47")
te <- round(mean(bmi_sd$BMICLASS2))
bmi_tx <- DO_1a %>%
  filter(fips == "48")
tx <- round(mean(bmi_tx$BMICLASS2))
bmi_ut <- DO_1a %>%
  filter(fips == "49")
ut <- round(mean(bmi_ut$BMICLASS2))
bmi_vt <- DO_1a %>%
  filter(fips == "50")
vt <- round(mean(bmi_vt$BMICLASS2))
bmi_va <- DO_1a %>%
  filter(fips == "51")
va <- round(mean(bmi_va$BMICLASS2))
bmi_wa <- DO_1a %>%
  filter(fips == "53")
wa <- round(mean(bmi_wa$BMICLASS2))
bmi_wv <- DO_1a %>%
  filter(fips == "54")
wv <- round(mean(bmi_wv$BMICLASS2))
bmi_wi <- DO_1a %>%
  filter(fips == "55")
wi <- round(mean(bmi_wi$BMICLASS2))
bmi_wy <- DO_1a %>%
  filter(fips == "56")
wy <- round(mean(bmi_wy$BMICLASS2))
fips <- c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56)
stateval <- c(al, ak, az, ar, ca, co, ct, de, fl, ga, hi, id, il, IN, ia, ks, ky, la, me, md, ma, mi, mn, ms, mo, mt, ne, nv, nh, nj, nm, ny, nc, nd, oh, ok, or, pa, ri, sc, sd, te, tx, ut, vt, va, wa, wv, wi, wy)
df <- data.frame(cbind(fips, stateval)) #data frame for mapping. It does appear that no state has an average in the 95th+ percentile.
df$stateval <- factor(as.integer(df$stateval), levels = c(1,2,3), labels = c("<5th perc","5-85th perc", ">85th perc"))

#making the new map
colORs <- brewer.pal(3,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = df, values = "stateval") + scale_fill_manual(values = colORsp(3)) + labs(title = "BMI Classification of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "BMI Class of Children") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))

#MAP 2: Using Mode instead of mean----------------------
#Averaging out variables for mapping before factorizing.
DO_1a <- dplyr::rename(DO_1, fips = FIPSST)
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
bmi_al <- DO_1a %>%
  filter(fips == "01")
al <- getmode(bmi_al$OVERWEIGHT)
bmi_ak <- DO_1a %>%
  filter(fips == "02")
ak <- getmode(bmi_ak$OVERWEIGHT)
bmi_az <- DO_1a %>%
  filter(fips == "04")
az <- getmode(bmi_az$OVERWEIGHT)
bmi_ar <- DO_1a %>%
  filter(fips == "05")
ar <- getmode(bmi_ar$OVERWEIGHT)
bmi_ca <- DO_1a %>%
  filter(fips == "06")
ca <- getmode(bmi_ca$OVERWEIGHT)
bmi_co <- DO_1a %>%
  filter(fips == "08")
co <- getmode(bmi_co$OVERWEIGHT)
bmi_ct <- DO_1a %>%
  filter(fips == "09")
ct <- getmode(bmi_ct$OVERWEIGHT)
bmi_de <- DO_1a %>%
  filter(fips == "10")
de <- getmode(bmi_de$OVERWEIGHT)
bmi_fl <- DO_1a %>%
  filter(fips == "12")
fl <- getmode(bmi_fl$OVERWEIGHT)
bmi_ga <- DO_1a %>%
  filter(fips == "13")
ga <- getmode(bmi_ga$OVERWEIGHT)
bmi_hi <- DO_1a %>%
  filter(fips == "15")
hi <- getmode(bmi_hi$OVERWEIGHT)
bmi_id <- DO_1a %>%
  filter(fips == "16")
id <- getmode(bmi_id$OVERWEIGHT)
bmi_il <- DO_1a %>%
  filter(fips == "17")
il <- getmode(bmi_il$OVERWEIGHT)
bmi_in <- DO_1a %>%
  filter(fips == "18")
IN <- getmode(bmi_in$OVERWEIGHT)
bmi_ia <- DO_1a %>%
  filter(fips == "19")
ia <- getmode(bmi_ia$OVERWEIGHT)
bmi_ks <- DO_1a %>%
  filter(fips == "20")
ks <- getmode(bmi_ks$OVERWEIGHT)
bmi_ky <- DO_1a %>%
  filter(fips == "21")
ky <- getmode(bmi_ky$OVERWEIGHT)
bmi_la <- DO_1a %>%
  filter(fips == "22")
la <- getmode(bmi_la$OVERWEIGHT)
bmi_me <- DO_1a %>%
  filter(fips == "23")
me <- getmode(bmi_me$OVERWEIGHT)
bmi_md <- DO_1a %>%
  filter(fips == "24")
md <- getmode(bmi_md$OVERWEIGHT)
bmi_ma <- DO_1a %>%
  filter(fips == "25")
ma <- getmode(bmi_ma$OVERWEIGHT)
bmi_mi <- DO_1a %>%
  filter(fips == "26")
mi <- getmode(bmi_mi$OVERWEIGHT)
bmi_mn <- DO_1a %>%
  filter(fips == "27")
mn <- getmode(bmi_mn$OVERWEIGHT)
bmi_ms <- DO_1a %>%
  filter(fips == "28")
ms <- getmode(bmi_ms$OVERWEIGHT)
bmi_mo <- DO_1a %>%
  filter(fips == "29")
mo <- getmode(bmi_mo$OVERWEIGHT)
bmi_mt <- DO_1a %>%
  filter(fips == "30")
mt <- getmode(bmi_mt$OVERWEIGHT)
bmi_ne <- DO_1a %>%
  filter(fips == "31")
ne <- getmode(bmi_ne$OVERWEIGHT)
bmi_nv <- DO_1a %>%
  filter(fips == "32")
nv <- getmode(bmi_nv$OVERWEIGHT)
bmi_nh <- DO_1a %>%
  filter(fips == "33")
nh <- getmode(bmi_nh$OVERWEIGHT)
bmi_nj <- DO_1a %>%
  filter(fips == "34")
nj <- getmode(bmi_nj$OVERWEIGHT)
bmi_nm <- DO_1a %>%
  filter(fips == "35")
nm <- getmode(bmi_nm$OVERWEIGHT)
bmi_ny <- DO_1a %>%
  filter(fips == "36")
ny <- getmode(bmi_ny$OVERWEIGHT)
bmi_nc <- DO_1a %>%
  filter(fips == "37")
nc <- getmode(bmi_nc$OVERWEIGHT)
bmi_nd <- DO_1a %>%
  filter(fips == "38")
nd <- getmode(bmi_nd$OVERWEIGHT)
bmi_oh <- DO_1a %>%
  filter(fips == "39")
oh <- getmode(bmi_oh$OVERWEIGHT)
bmi_ok <- DO_1a %>%
  filter(fips == "40")
ok <- getmode(bmi_ok$OVERWEIGHT)
bmi_or <- DO_1a %>%
  filter(fips == "41")
or <- getmode(bmi_or$OVERWEIGHT)
bmi_pa <- DO_1a %>%
  filter(fips == "42")
pa <- getmode(bmi_pa$OVERWEIGHT)
bmi_ri <- DO_1a %>%
  filter(fips == "44")
ri <- getmode(bmi_ri$OVERWEIGHT)
bmi_sc <- DO_1a %>%
  filter(fips == "45")
sc <- getmode(bmi_sc$OVERWEIGHT)
bmi_sd <- DO_1a %>%
  filter(fips == "46")
sd <- getmode(bmi_sd$OVERWEIGHT)
bmi_te <- DO_1a %>%
  filter(fips == "47")
te <- getmode(bmi_sd$OVERWEIGHT)
bmi_tx <- DO_1a %>%
  filter(fips == "48")
tx <- getmode(bmi_tx$OVERWEIGHT)
bmi_ut <- DO_1a %>%
  filter(fips == "49")
ut <- getmode(bmi_ut$OVERWEIGHT)
bmi_vt <- DO_1a %>%
  filter(fips == "50")
vt <- getmode(bmi_vt$OVERWEIGHT)
bmi_va <- DO_1a %>%
  filter(fips == "51")
va <- getmode(bmi_va$OVERWEIGHT)
bmi_wa <- DO_1a %>%
  filter(fips == "53")
wa <- getmode(bmi_wa$OVERWEIGHT)
bmi_wv <- DO_1a %>%
  filter(fips == "54")
wv <- getmode(bmi_wv$OVERWEIGHT)
bmi_wi <- DO_1a %>%
  filter(fips == "55")
wi <- getmode(bmi_wi$OVERWEIGHT)
bmi_wy <- DO_1a %>%
  filter(fips == "56")
wy <- getmode(bmi_wy$OVERWEIGHT)
fips <- c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56)
stateval <- c(al, ak, az, ar, ca, co, ct, de, fl, ga, hi, id, il, IN, ia, ks, ky, la, me, md, ma, mi, mn, ms, mo, mt, ne, nv, nh, nj, nm, ny, nc, nd, oh, ok, or, pa, ri, sc, sd, te, tx, ut, vt, va, wa, wv, wi, wy)
df <- data.frame(cbind(fips, stateval))
#Should I be taking the average for ranked variables or the mode of what is most common (e.g. for purely categorical variables?) Example with mode below.
#MAP 2: OVERWEIGHT Geospatial Visualization
df$stateval <- factor(as.integer(df$stateval), levels = c(1,2), labels = c("Overweight","Not Overweight"))
colORs <- brewer.pal(2,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = df, values = "stateval") + scale_fill_manual(values = colORsp(2)) + labs(title = "Overweight Classification of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "Overweight Classification") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))

#MAP 3: Using mode instead of mean for race--------------
DO_1a <- dplyr::rename(DO_1, fips = FIPSST)
bmi_al <- DO_1a %>%
  filter(fips == "01")
al <- getmode(bmi_al$SC_RACE_R)
bmi_ak <- DO_1a %>%
  filter(fips == "02")
ak <- getmode(bmi_ak$SC_RACE_R)
bmi_az <- DO_1a %>%
  filter(fips == "04")
az <- getmode(bmi_az$SC_RACE_R)
bmi_ar <- DO_1a %>%
  filter(fips == "05")
ar <- getmode(bmi_ar$SC_RACE_R)
bmi_ca <- DO_1a %>%
  filter(fips == "06")
ca <- getmode(bmi_ca$SC_RACE_R)
bmi_co <- DO_1a %>%
  filter(fips == "08")
co <- getmode(bmi_co$SC_RACE_R)
bmi_ct <- DO_1a %>%
  filter(fips == "09")
ct <- getmode(bmi_ct$SC_RACE_R)
bmi_de <- DO_1a %>%
  filter(fips == "10")
de <- getmode(bmi_de$SC_RACE_R)
bmi_fl <- DO_1a %>%
  filter(fips == "12")
fl <- getmode(bmi_fl$SC_RACE_R)
bmi_ga <- DO_1a %>%
  filter(fips == "13")
ga <- getmode(bmi_ga$SC_RACE_R)
bmi_hi <- DO_1a %>%
  filter(fips == "15")
hi <- getmode(bmi_hi$SC_RACE_R)
bmi_id <- DO_1a %>%
  filter(fips == "16")
id <- getmode(bmi_id$SC_RACE_R)
bmi_il <- DO_1a %>%
  filter(fips == "17")
il <- getmode(bmi_il$SC_RACE_R)
bmi_in <- DO_1a %>%
  filter(fips == "18")
IN <- getmode(bmi_in$SC_RACE_R)
bmi_ia <- DO_1a %>%
  filter(fips == "19")
ia <- getmode(bmi_ia$SC_RACE_R)
bmi_ks <- DO_1a %>%
  filter(fips == "20")
ks <- getmode(bmi_ks$SC_RACE_R)
bmi_ky <- DO_1a %>%
  filter(fips == "21")
ky <- getmode(bmi_ky$SC_RACE_R)
bmi_la <- DO_1a %>%
  filter(fips == "22")
la <- getmode(bmi_la$SC_RACE_R)
bmi_me <- DO_1a %>%
  filter(fips == "23")
me <- getmode(bmi_me$SC_RACE_R)
bmi_md <- DO_1a %>%
  filter(fips == "24")
md <- getmode(bmi_md$SC_RACE_R)
bmi_ma <- DO_1a %>%
  filter(fips == "25")
ma <- getmode(bmi_ma$SC_RACE_R)
bmi_mi <- DO_1a %>%
  filter(fips == "26")
mi <- getmode(bmi_mi$SC_RACE_R)
bmi_mn <- DO_1a %>%
  filter(fips == "27")
mn <- getmode(bmi_mn$SC_RACE_R)
bmi_ms <- DO_1a %>%
  filter(fips == "28")
ms <- getmode(bmi_ms$SC_RACE_R)
bmi_mo <- DO_1a %>%
  filter(fips == "29")
mo <- getmode(bmi_mo$SC_RACE_R)
bmi_mt <- DO_1a %>%
  filter(fips == "30")
mt <- getmode(bmi_mt$SC_RACE_R)
bmi_ne <- DO_1a %>%
  filter(fips == "31")
ne <- getmode(bmi_ne$SC_RACE_R)
bmi_nv <- DO_1a %>%
  filter(fips == "32")
nv <- getmode(bmi_nv$SC_RACE_R)
bmi_nh <- DO_1a %>%
  filter(fips == "33")
nh <- getmode(bmi_nh$SC_RACE_R)
bmi_nj <- DO_1a %>%
  filter(fips == "34")
nj <- getmode(bmi_nj$SC_RACE_R)
bmi_nm <- DO_1a %>%
  filter(fips == "35")
nm <- getmode(bmi_nm$SC_RACE_R)
bmi_ny <- DO_1a %>%
  filter(fips == "36")
ny <- getmode(bmi_ny$SC_RACE_R)
bmi_nc <- DO_1a %>%
  filter(fips == "37")
nc <- getmode(bmi_nc$SC_RACE_R)
bmi_nd <- DO_1a %>%
  filter(fips == "38")
nd <- getmode(bmi_nd$SC_RACE_R)
bmi_oh <- DO_1a %>%
  filter(fips == "39")
oh <- getmode(bmi_oh$SC_RACE_R)
bmi_ok <- DO_1a %>%
  filter(fips == "40")
ok <- getmode(bmi_ok$SC_RACE_R)
bmi_or <- DO_1a %>%
  filter(fips == "41")
or <- getmode(bmi_or$SC_RACE_R)
bmi_pa <- DO_1a %>%
  filter(fips == "42")
pa <- getmode(bmi_pa$SC_RACE_R)
bmi_ri <- DO_1a %>%
  filter(fips == "44")
ri <- getmode(bmi_ri$SC_RACE_R)
bmi_sc <- DO_1a %>%
  filter(fips == "45")
sc <- getmode(bmi_sc$SC_RACE_R)
bmi_sd <- DO_1a %>%
  filter(fips == "46")
sd <- getmode(bmi_sd$SC_RACE_R)
bmi_te <- DO_1a %>%
  filter(fips == "47")
te <- getmode(bmi_sd$SC_RACE_R)
bmi_tx <- DO_1a %>%
  filter(fips == "48")
tx <- getmode(bmi_tx$SC_RACE_R)
bmi_ut <- DO_1a %>%
  filter(fips == "49")
ut <- getmode(bmi_ut$SC_RACE_R)
bmi_vt <- DO_1a %>%
  filter(fips == "50")
vt <- getmode(bmi_vt$SC_RACE_R)
bmi_va <- DO_1a %>%
  filter(fips == "51")
va <- getmode(bmi_va$SC_RACE_R)
bmi_wa <- DO_1a %>%
  filter(fips == "53")
wa <- getmode(bmi_wa$SC_RACE_R)
bmi_wv <- DO_1a %>%
  filter(fips == "54")
wv <- getmode(bmi_wv$SC_RACE_R)
bmi_wi <- DO_1a %>%
  filter(fips == "55")
wi <- getmode(bmi_wi$SC_RACE_R)
bmi_wy <- DO_1a %>%
  filter(fips == "56")
wy <- getmode(bmi_wy$SC_RACE_R)
fips <- c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56)
stateval <- c(al, ak, az, ar, ca, co, ct, de, fl, ga, hi, id, il, IN, ia, ks, ky, la, me, md, ma, mi, mn, ms, mo, mt, ne, nv, nh, nj, nm, ny, nc, nd, oh, ok, or, pa, ri, sc, sd, te, tx, ut, vt, va, wa, wv, wi, wy)
df <- data.frame(cbind(fips, stateval))
df$stateval <- factor(as.integer(df$stateval), levels = c(1,2,3,4,5,6,7), labels = c("White","Black or African American","American Indian or Alaska Native","Asian","Native Hawaiian or Pacific Islander","Other Race","Two or More Races"))

#creating the map
colORs <- brewer.pal(6,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = df, values = "stateval") + scale_fill_manual(values = colORsp(6)) + labs(title = "Racial Categories of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "Racial Category") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))
```
