---
title: "NCHS_ResearchProject_BakerS"
author: "Sunderland Baker"
date: '2022-06-29'
output: pdf_document
---

``` {r upload and organize data}
library(haven)
library(dplyr)
library(tidyverse)
#Uploading data from OneDrive repository.
screener_2018 <- read_sas("C:/Users/Sunderland Baker/OneDrive - Colorado College/JUNIOR YEAR/BIOS6670/NCHS Research Project/nsch_2018_screener.sas7bdat")
topical_2018 <- read_sas("C:/Users/Sunderland Baker/OneDrive - Colorado College/JUNIOR YEAR/BIOS6670/NCHS Research Project/nsch_2018_topical.sas7bdat")
screener_2019 <- read_sas("C:/Users/Sunderland Baker/OneDrive - Colorado College/JUNIOR YEAR/BIOS6670/NCHS Research Project/nsch_2019_screener.sas7bdat")
topical_2019 <- read_sas("C:/Users/Sunderland Baker/OneDrive - Colorado College/JUNIOR YEAR/BIOS6670/NCHS Research Project/nsch_2019_topical.sas7bdat")

#Data variable renaming and merging by ID.
screener_2018 <- rename(screener_2018, HHID = HHIDS)
st_2018 <- merge(screener_2018, topical_2018, by="HHID")
screener_2019 <- rename(screener_2019, HHID = HHIDS)
st_2019 <- merge(screener_2019, topical_2019, by="HHID")
st_2018$YEAR <- st_2018$YEAR.x
st_2019$YEAR <- st_2019$YEAR.x
st_2018$FIPS <- st_2018$FIPSST.x
st_2019$FIPS <- st_2019$FIPSST.x
st_2018_1 <- st_2018 %>% select(YEAR, FIPS, SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, K2Q32A, K2Q32B, K2Q32C, K2Q33A, K2Q33B, K2Q33C, C_K2Q17,C_K2Q22, TENURE.x, TOTKIDS_R.x, A1_BORN, A1_MARITAL, A1_MENTHEALTH, A1_PHYSHEALTH, ACE1, ACE7, HCABILITY, BIRTHWT, BREATHING, CAVITIES, DENTALSERV3, FAMILY_R, FPL_I1, HIGRADE_TVIS, K10Q11, K10Q12, K10Q40_R, K10Q41_R, K11Q62, K2Q40A, K2Q40C, K2Q41A, K2Q41C, K5Q20_R, K6Q73_R, K7Q30, K7Q38, K8Q31, K9Q41, MAKEFRIEND, METRO_YN.x, S9Q34, SC_K2Q16, SUBABUSE)
st_2019_1 <- st_2019 %>% select(YEAR, FIPS, SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, K2Q32A, K2Q32B, K2Q32C, K2Q33A, K2Q33B, K2Q33C, C_K2Q17,C_K2Q22, TENURE.x, TOTKIDS_R.x, A1_BORN, A1_MARITAL, A1_MENTHEALTH, A1_PHYSHEALTH, ACE1, ACE7, HCABILITY, BIRTHWT, BREATHING, CAVITIES, DENTALSERV3, FAMILY_R, FPL_I1, HIGRADE_TVIS, K10Q11, K10Q12, K10Q40_R, K10Q41_R, K11Q62, K2Q40A, K2Q40C, K2Q41A, K2Q41C, K5Q20_R, K6Q73_R, K7Q30, K7Q38, K8Q31, K9Q41, MAKEFRIEND, METRO_YN.x, S9Q34, SC_K2Q16, SUBABUSE)
#K2Q17 is pediatric disability, FIPSST.x is the FIPS code (geographic info), TENURE is how the household is owned, TOTKIDS_R is how many kids in house, A1/2_BORN is foreign-born parents, A1/2_MARITAL is parent marital status, A1/2_MENT/PHYSHEALTH is parent mental/physical health, ACE1 is food/housing insecurity, ACE7 is violence experienced [trauma vars], HCABILITY is health affecting ability, BIRTHWT is low/norm birth weight, BREATHING is breathing difficulties, BULLIED_R is getting bullied (freq), CAVITIES is having cavities, DENTALSERV3 is getting dental care on toothbrushing, FAMILY_R is family dynamic, FPL_I1 is family-poverty ratio, HIGRADE_TVIS is the parental level of education, K10Q11 is neighborhood walking paths, K10Q12 is parks/playgrounds, K10Q40_R is neighborhood safety, K10Q41_R is school safety, K11Q62 is FRLP usage in school by children, K2Q40A/C is asthma/its severity, K2Q41A/C is diabetes/its severity, K5Q20_R is healthcare access, K6Q73_R is behavioral resilience, K7Q30 sports involvement, K7Q38 child employment, K8Q31 is parental perceptions of child rearing, K9Q41 is smoking in house, MAKEFRIEND is child's socializability, METRO_YN is living in a metro area, S9Q33 is receiving WIC, SC_K2Q16 is disability impacting tasks, SUBABUSE is child with substance abuse.

#Next steps: Filter just the ages 13-18 and CVD, and append by year.
data <- rbind(st_2018_1, st_2019_1)
DataOfficial <- data %>% filter(data$SC_AGE_YEARS>=13 & data$SC_AGE_YEARS<=18)
dim(DataOfficial)
```

``` {r small dataset}
#Variable count = 21 (mainly the ones previously-specified as well as home-life and social and emotional variables.) N=675
st_2018_21 <- st_2018_1 %>% select(FIPS, SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, ACE1, ACE7, MAKEFRIEND, SUBABUSE, K2Q32A, K2Q32B, K2Q32C, K2Q33A, K2Q33B, K2Q33C)
st_2019_21 <- st_2019_1 %>% select(FIPS, SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, ACE1, ACE7, MAKEFRIEND, SUBABUSE, K2Q32A, K2Q32B, K2Q32C, K2Q33A, K2Q33B, K2Q33C)
st_2018_21c <- st_2018_21[complete.cases(st_2018_21),]
st_2019_21c <- st_2019_21[complete.cases(st_2019_21),]
st_1819_c <- rbind(st_2018_21c, st_2019_21c) #combined dataset
st_1819_c <- st_1819_c %>% filter(st_1819_c$SC_AGE_YEARS>=13 & st_1819_c$SC_AGE_YEARS<=18)
#Factorizing variables for proper output.
st_1819_c$BMICLASS <- factor(as.integer(st_1819_c$BMICLASS), levels = c(1,2,3,4), labels = c("0-5th perc","5-85th perc", "85-95th perc", "95-100th perc"))
st_1819_c$FIPS <- factor(as.integer(st_1819_c$FIPS), levels = c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56), labels = c("Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","District of Columbia","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"))
st_1819_c$SC_AGE_YEARS <- factor(as.integer(st_1819_c$SC_AGE_YEARS), levels = c(13,14,15,16,17,18))
st_1819_c$SC_HISPANIC_R <- factor(as.integer(st_1819_c$SC_HISPANIC_R), levels = c(1,2), labels = c("Hispanic/Latino Origin","Not Hispanic/Latino"))
st_1819_c$SC_RACE_R <- factor(as.integer(st_1819_c$SC_RACE_R), levels = c(1,2,3,4,5,7), labels = c("White","Black or African American","American Indian or Alaska Native","Asian","Native Hawaiian or Pacific Islander","Two or More Races"))
st_1819_c$SC_SEX <- factor(as.integer(st_1819_c$SC_SEX), levels = c(1,2), labels = c("Male","Female"))
st_1819_c$OVERWEIGHT <- factor(as.integer(st_1819_c$OVERWEIGHT), levels = c(1,2), labels = c("Yes","No"))
st_1819_c$PHYSACTIV <- factor(as.integer(st_1819_c$PHYSACTIV), levels = c(1,2,3,4), labels = c("0 days","1-3 days","4-6 days","Every day"))
st_1819_c$SCREENTIME <- factor(as.integer(st_1819_c$SCREENTIME), levels = c(1,2,3,4,5), labels = c("<1 hour","1 hour","2 hours","3 hours",">4 hours"))
st_1819_c$HOURSLEEP <- factor(as.integer(st_1819_c$HOURSLEEP), levels = c(1,2,3,4,5,6,7), labels = c("<6 hours","6 hours","7 hours","8 hours","9 hours","10 hours",">11 hours"))
st_1819_c$ACE1 <- factor(as.integer(st_1819_c$ACE1), levels = c(1,2,3,4), labels = c("Never","Rarely","Somewhat Often","Very Often"))
st_1819_c$ACE7 <- factor(as.integer(st_1819_c$ACE7), levels = c(1,2), labels = c("Victim of Violence","Not Victim of Violence"))
st_1819_c$MAKEFRIEND <- factor(as.integer(st_1819_c$MAKEFRIEND), levels = c(1,2,3), labels = c("No difficulty","Some difficulty","A lot of difficulty"))
st_1819_c$SUBABUSE <- factor(as.integer(st_1819_c$SUBABUSE), levels = c(1,2), labels = c("Substance Use Disorder","No Substance Abuse"))
st_1819_c$K2Q32A <- factor(as.integer(st_1819_c$K2Q32A), levels = c(1,2), labels = c("Depression","No Depression"))
st_1819_c$K2Q32B <- factor(as.integer(st_1819_c$K2Q32B), levels = c(1,2), labels = c("Depression Currently","No Depression Currently"))
st_1819_c$K2Q32C <- factor(as.integer(st_1819_c$K2Q32C), levels = c(1,2,3), labels = c("Mild","Moderate","Severe"))
st_1819_c$K2Q33A <- factor(as.integer(st_1819_c$K2Q33A), levels = c(1,2), labels = c("Anxiety","No Anxiety"))
st_1819_c$K2Q33B <- factor(as.integer(st_1819_c$K2Q33B), levels = c(1,2), labels = c("Anxiety Currently","No Anxiety Currently"))
st_1819_c$K2Q33C <- factor(as.integer(st_1819_c$K2Q33C), levels = c(1,2,3), labels = c("Mild","Moderate","Severe"))
st_1819_c <- st_1819_c[complete.cases(st_1819_c),]

#Implementing random forest
library(randomForest)
set.seed(2022)
Train <- sample(nrow(st_1819_c), 0.8*nrow(st_1819_c),replace=FALSE)
TrainSet <- st_1819_c[Train,]
TestSet <- st_1819_c[-Train,] #whatever is not part of trainset
summary(TrainSet)
summary(TestSet)
options(warn=-1)
RF1 <- randomForest(formula = BMICLASS ~ ., data = TrainSet, importance=TRUE)
RF1 #yields a confusion matrix with variables factorized
predTrain <- predict(RF1, TrainSet, type = "class")
predTest <- predict(RF1, TestSet, type = "class")
table(predTrain,TrainSet$BMICLASS);
table(predTest,TestSet$BMICLASS);
importance(RF1)
varImpPlot(RF1,sort=TRUE,n.var=min(21, nrow(RF1$importance)),main="Variable Importance Plot for Obesity Predictions with Psychoecological Variables")
```

```{r small dataset}
#Variable count = 15 (og vars) N=545
st_2018_15 <- st_2018_1 %>% select(SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, K2Q32A, K2Q32B, K2Q32C, K2Q33A, K2Q33B, K2Q33C)
st_2019_15 <- st_2019_1 %>% select(SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, K2Q32A, K2Q32B, K2Q32C, K2Q33A, K2Q33B, K2Q33C)
st_2018_15c <- st_2018_15[complete.cases(st_2018_15),]
st_2019_15c <- st_2019_15[complete.cases(st_2019_15),]
st_1819_15c <- rbind(st_2018_15c, st_2019_15c) #combined dataset
st_1819_15c <- st_1819_15c %>% filter(st_1819_15c$SC_AGE_YEARS>=13 & st_1819_15c$SC_AGE_YEARS<=18)

#Factorizing variables for proper output.
st_1819_15c$BMICLASS <- factor(as.integer(st_1819_15c$BMICLASS), levels = c(1,2,3,4), labels = c("0-5th perc","5-85th perc", "85-95th perc", "95-100th perc"))
st_1819_15c$FIPS <- factor(as.integer(st_1819_15c$FIPS), levels = c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56), labels = c("Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","District of Columbia","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"))
st_1819_15c$SC_AGE_YEARS <- factor(as.integer(st_1819_15c$SC_AGE_YEARS), levels = c(13,14,15,16,17,18))
st_1819_15c$SC_HISPANIC_R <- factor(as.integer(st_1819_15c$SC_HISPANIC_R), levels = c(1,2), labels = c("Hispanic/Latino Origin","Not Hispanic/Latino"))
st_1819_15c$SC_RACE_R <- factor(as.integer(st_1819_15c$SC_RACE_R), levels = c(1,2,3,4,5,7), labels = c("White","Black or African American","American Indian or Alaska Native","Asian","Native Hawaiian or Pacific Islander","Two or More Races"))
st_1819_15c$SC_SEX <- factor(as.integer(st_1819_15c$SC_SEX), levels = c(1,2), labels = c("Male","Female"))
st_1819_15c$OVERWEIGHT <- factor(as.integer(st_1819_15c$OVERWEIGHT), levels = c(1,2), labels = c("Yes","No"))
st_1819_15c$PHYSACTIV <- factor(as.integer(st_1819_15c$PHYSACTIV), levels = c(1,2,3,4), labels = c("0 days","1-3 days","4-6 days","Every day"))
st_1819_15c$SCREENTIME <- factor(as.integer(st_1819_15c$SCREENTIME), levels = c(1,2,3,4,5), labels = c("<1 hour","1 hour","2 hours","3 hours",">4 hours"))
st_1819_15c$HOURSLEEP <- factor(as.integer(st_1819_15c$HOURSLEEP), levels = c(1,2,3,4,5,6,7), labels = c("<6 hours","6 hours","7 hours","8 hours","9 hours","10 hours",">11 hours"))
st_1819_15c$K2Q32A <- factor(as.integer(st_1819_15c$K2Q32A), levels = c(1,2), labels = c("Depression","No Depression"))
st_1819_15c$K2Q32B <- factor(as.integer(st_1819_15c$K2Q32B), levels = c(1,2), labels = c("Depression Currently","No Depression Currently"))
st_1819_15c$K2Q32C <- factor(as.integer(st_1819_15c$K2Q32C), levels = c(1,2,3), labels = c("Mild","Moderate","Severe"))
st_1819_15c$K2Q33A <- factor(as.integer(st_1819_15c$K2Q33A), levels = c(1,2), labels = c("Anxiety","No Anxiety"))
st_1819_15c$K2Q33B <- factor(as.integer(st_1819_15c$K2Q33B), levels = c(1,2), labels = c("Anxiety Currently","No Anxiety Currently"))
st_1819_15c$K2Q33C <- factor(as.integer(st_1819_15c$K2Q33C), levels = c(1,2,3), labels = c("Mild","Moderate","Severe"))
st_1819_15c <- st_1819_15c[complete.cases(st_1819_15c),]

#Implementing random forest
library(randomForest)
set.seed(2022)
Train <- sample(nrow(st_1819_15c), 0.8*nrow(st_1819_15c),replace=FALSE)
TrainSet <- st_1819_15c[Train,]
TestSet <- st_1819_15c[-Train,] #whatever is not part of trainset
summary(TrainSet)
summary(TestSet)
options(warn=-1)
RF2 <- randomForest(formula = BMICLASS ~ ., data = TrainSet, importance=TRUE)
RF2 #does not yield confusion matrix
predTrain <- predict(RF2, TrainSet, type = "class")
predTest <- predict(RF2, TestSet, type = "class")
table(predTrain,TrainSet$BMICLASS);
table(predTest,TestSet$BMICLASS);
importance(RF2)
varImpPlot(RF2,sort=TRUE,n.var=min(15, nrow(RF2$importance)),main="Variable Importance Plot for Obesity Predictions with Psychoecological Variables")
```

```{r large dataset}
#Variable count = 37. 
st_2018_1a <- st_2018 %>% select(FIPS, SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, K2Q32A, K2Q32B, K2Q32C, K2Q33A, K2Q33B, K2Q33C, C_K2Q22, TENURE.x, TOTKIDS_R.x, A1_MARITAL, A1_MENTHEALTH, A1_PHYSHEALTH, ACE1, ACE7, FPL_I1, HIGRADE_TVIS, K10Q11, K10Q12, K10Q40_R, K10Q41_R, K11Q62, K6Q73_R, K7Q30, MAKEFRIEND, SUBABUSE)
st_2019_1a <- st_2019 %>% select(FIPS, SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, K2Q32A, K2Q32B, K2Q32C, K2Q33A, K2Q33B, K2Q33C, C_K2Q22, TENURE.x, TOTKIDS_R.x, A1_MARITAL, A1_MENTHEALTH, A1_PHYSHEALTH, ACE1, ACE7, FPL_I1, HIGRADE_TVIS, K10Q11, K10Q12, K10Q40_R, K10Q41_R, K11Q62, K6Q73_R, K7Q30, MAKEFRIEND, SUBABUSE)
comb <- rbind(st_2018_1a,st_2019_1a)
DataOf <- comb %>% filter(comb$SC_AGE_YEARS>=13 & comb$SC_AGE_YEARS<=18)
st_1819_37c <- DataOf[complete.cases(DataOf),]
dim(st_1819_37c)
#Still need to decrease var count, but I really like this list, since it yields zero entries upon filtering NA values.
```

```{r official dataset work, echo=TRUE}
#Producing official dataset, first loading relevant libraries.
library(randomForest)

#add plotting libraries needed
t_2018 <- topical_2018 %>% select(YEAR, FIPSST, SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, K2Q32A, K2Q33A, ACE1, ACE3, ACE4, ACE5, ACE6, ACE7, ACE8, ACE9, ACE10)
t_2019 <- topical_2019 %>% select(YEAR, FIPSST, SC_AGE_YEARS, SC_HISPANIC_R, SC_RACE_R, SC_SEX, BMICLASS, OVERWEIGHT, PHYSACTIV, SCREENTIME, HOURSLEEP, K2Q32A, K2Q33A, ACE1, ACE3, ACE4, ACE5, ACE6, ACE7, ACE8, ACE9, ACE10)
dta <- rbind(t_2018, t_2018)
DataOff <- dta %>% filter(dta$SC_AGE_YEARS>=13 & dta$SC_AGE_YEARS<=18)
DO_1 <- DataOff[complete.cases(DataOff[ , c("SC_AGE_YEARS","SC_HISPANIC_R", "SC_RACE_R", "SC_SEX", "BMICLASS", "PHYSACTIV", "SCREENTIME", "HOURSLEEP", "K2Q33A", "K2Q32A","ACE1","ACE3","ACE4","ACE5","ACE6","ACE7","ACE8","ACE9","ACE10")]), ] 
dim(DO_1) #checking the dimensions of official data frame
DO_1$BMICLASS2 <- ifelse(DO_1$BMICLASS %in% c(1,2), 1, ifelse(
  DO_1$BMICLASS==3, 2, 3))
#write.csv(DataOfficial_1, "NSCHRandomForest-Clean-070622.csv", row.names=F)

#Variable recategorization for optimal RF output
DO_1$BMICLASS2 <- factor(as.integer(DO_1$BMICLASS2), levels = c(1,2,3), labels = c("0-5th perc","5-95th perc", "95-100th perc"))
DO_1$FIPSST <- factor(as.integer(DO_1$FIPSST), levels = c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56), labels = c("Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","District of Columbia","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"))
DO_1$SC_AGE_YEARS <- factor(as.integer(DO_1$SC_AGE_YEARS), levels = c(13,14,15,16,17,18))
DO_1$SC_HISPANIC_R <- factor(as.integer(DO_1$SC_HISPANIC_R), levels = c(1,2), labels = c("Hispanic/Latino Origin","Not Hispanic/Latino"))
DO_1$SC_RACE_R <- factor(as.integer(DO_1$SC_RACE_R), levels = c(1,2,3,4,5,7), labels = c("White","Black or African American","American Indian or Alaska Native","Asian","Native Hawaiian or Pacific Islander","Two or More Races"))
DO_1$SC_SEX <- factor(as.integer(DO_1$SC_SEX), levels = c(1,2), labels = c("Male","Female"))
DO_1$OVERWEIGHT <- factor(as.integer(DO_1$OVERWEIGHT), levels = c(1,2), labels = c("Yes","No"))
DO_1$PHYSACTIV <- factor(as.integer(DO_1$PHYSACTIV), levels = c(1,2,3,4), labels = c("0 days","1-3 days","4-6 days","Every day"))
DO_1$SCREENTIME <- factor(as.integer(DO_1$SCREENTIME), levels = c(1,2,3,4,5), labels = c("<1 hour","1 hour","2 hours","3 hours",">4 hours"))
DO_1$HOURSLEEP <- factor(as.integer(DO_1$HOURSLEEP), levels = c(1,2,3,4,5,6,7), labels = c("<6 hours","6 hours","7 hours","8 hours","9 hours","10 hours",">11 hours"))
DO_1$K2Q32A <- factor(as.integer(DO_1$K2Q32A), levels = c(1,2), labels = c("Depression","No Depression"))
DO_1$K2Q33A <- factor(as.integer(DO_1$K2Q33A), levels = c(1,2), labels = c("Anxiety","No Anxiety"))
newvar <- c()
for (k in 1:19684){
  val <- 0
  if (DO_1$ACE1[k]==3 | DO_1$ACE1[k]==4){
    val <- val + 1}
  if (DO_1$ACE3[k]==1){
    val <- val + 1}
  if (DO_1$ACE4[k]==1){
    val <- val + 1}
  if (DO_1$ACE5[k]==1){
    val <- val + 1}
  if (DO_1$ACE6[k]==1){
    val <- val + 1}
  if (DO_1$ACE7[k]==1){
    val <- val + 1}
  if (DO_1$ACE8[k]==1){
    val <- val + 1}
  if (DO_1$ACE9[k]==1){
    val <- val + 1}
  if (DO_1$ACE10[k]==1){
    val <- val + 1}
  newvar[k] <- val
}
DO_1$ACE_Count <- newvar
  
DO_1$ACE1 <- factor(as.integer(DO_1$ACE1), levels = c(1,2,3,4), labels = c("No Food Insecurity", "Rare Food Insecurity", "Often Food Insecurity", "Very Often Food Insecurity"))
DO_1$ACE3 <- factor(as.integer(DO_1$ACE3), levels = c(1,2), labels = c("Parents Divorced/Separated", "Parents Together"))
DO_1$ACE4 <- factor(as.integer(DO_1$ACE4), levels = c(1,2), labels = c("Parent Death", "No Parent Death"))
DO_1$ACE5 <- factor(as.integer(DO_1$ACE5), levels = c(1,2), labels = c("Parent Incarcerated", "Parent Not Incarcerated"))
DO_1$ACE6 <- factor(as.integer(DO_1$ACE6), levels = c(1,2), labels = c("Witnessed Domestic Violence", "No Domestic Violence"))
DO_1$ACE7 <- factor(as.integer(DO_1$ACE7), levels = c(1,2), labels = c("Victim of Violence", "Not Victim of Violence"))
DO_1$ACE8 <- factor(as.integer(DO_1$ACE8), levels = c(1,2), labels = c("Lived with Mentally Ill", "No Exposure to Mental Illness"))
DO_1$ACE9 <- factor(as.integer(DO_1$ACE9), levels = c(1,2), labels = c("Lived with Alcohol/Drug Abuse", "No Exposure to Alcohol/Drug Abuse"))
DO_1$ACE10 <- factor(as.integer(DO_1$ACE10), levels = c(1,2), labels = c("Racism Experienced", "No Racism Experienced"))

#Random Forest Model with All Pertinent Variables
na.exclude(DO_1)
set.seed(2022)
Train <- sample(nrow(DO_1), 0.8*nrow(DO_1),replace=FALSE)
TrainSet <- DO_1[Train,]
TestSet <- DO_1[-Train,] #whatever is not part of trainset
summary(TrainSet)
summary(TestSet)
options(warn=-1)
RF_DO1 <- randomForest(formula = BMICLASS2 ~ FIPSST + SC_AGE_YEARS + SC_HISPANIC_R + SC_RACE_R + SC_SEX + OVERWEIGHT + PHYSACTIV + SCREENTIME + HOURSLEEP + K2Q32A + K2Q33A + ACE1 + ACE3 + ACE4 + ACE5 + ACE6 + ACE7 + ACE8 + ACE9 + ACE10, data = TrainSet, importance=TRUE, na.action = na.roughfix)
RF_DO1 #yields a confusion matrix with variables factorized
predTrain <- predict(RF_DO1, TrainSet, type = "class")
predTest <- predict(RF_DO1, TestSet, type = "class")
table(predTrain,TrainSet$BMICLASS2);
table(predTest,TestSet$BMICLASS2);
importance(RF_DO1)
varImpPlot(RF_DO1,sort=TRUE,n.var=min(21, nrow(RF_DO1$importance)),main="Variable Importance Plot for Obesity Predictions with Psychoecological Variables")

#Random Forest Model with ACE Aggregate
na.exclude(DO_1)
set.seed(2022)
Train_2 <- sample(nrow(DO_1), 0.8*nrow(DO_1),replace=FALSE)
TrainSet_2 <- DO_1[Train,]
TestSet_2 <- DO_1[-Train,] #whatever is not part of trainset
summary(TrainSet_2)
summary(TestSet_2)
options(warn=-1)
RF2_DO1 <- randomForest(formula = BMICLASS2 ~ FIPSST + SC_AGE_YEARS + SC_HISPANIC_R + SC_RACE_R + SC_SEX + OVERWEIGHT + PHYSACTIV + SCREENTIME + HOURSLEEP + K2Q32A + K2Q33A + ACE_Count, data = TrainSet_2, importance=TRUE, na.action = na.roughfix)
RF2_DO1 #yields a confusion matrix with variables factorized
predTrain_2 <- predict(RF2_DO1, TrainSet_2, type = "class")
predTest_2 <- predict(RF2_DO1, TestSet_2, type = "class")
table(predTrain_2,TrainSet_2$BMICLASS2);
table(predTest_2,TestSet_2$BMICLASS2);
importance(RF2_DO1)
varImpPlot(RF2_DO1,sort=TRUE,n.var=min(21, nrow(RF2_DO1$importance)),main="Variable Importance Plot for Obesity Predictions with ACE Aggregate")

#Random Forest with Solely ACE Variables
na.exclude(DO_1)
set.seed(2022)
Train_3 <- sample(nrow(DO_1), 0.8*nrow(DO_1),replace=FALSE)
TrainSet_3 <- DO_1[Train,]
TestSet_3 <- DO_1[-Train,] #whatever is not part of trainset
summary(TrainSet_3)
summary(TestSet_3)
options(warn=-1)
RF3_DO1 <- randomForest(formula = BMICLASS2 ~ ACE1 + ACE3 + ACE4 + ACE5 + ACE6 + ACE7 + ACE8 + ACE9 + ACE10, data = TrainSet, importance=TRUE, na.action = na.roughfix)
RF3_DO1 #yields a confusion matrix with variables factorized
predTrain_3 <- predict(RF3_DO1, TrainSet_3, type = "class")
predTest_3 <- predict(RF3_DO1, TestSet_3, type = "class")
table(predTrain_3,TrainSet_3$BMICLASS2);
table(predTest_3,TestSet_3$BMICLASS2);
importance(RF3_DO1)
varImpPlot(RF3_DO1,sort=TRUE,n.var=min(21, nrow(RF3_DO1$importance)),main="Variable Importance Plot for Obesity Predictions with ACE Variables")

#US Map Plots 
library(usmap)
library(ggplot2)
library(openintro)
library(readxl)
library(statsr)
library(rio)
library(skimr)
library(broom)
library(RColorBrewer)
library(scales)
library(dplyr)
#Run til line 161 and then run this code.
DO_1a <- dplyr::rename(DO_1, fips = FIPSST)

#MAP 1: BMICLASS2 Geospatial Visualization
colORs <- brewer.pal(3,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = DO_1a, values = "BMICLASS2") + scale_fill_manual(values = colORsp(3)) + labs(title = "BMI Classification of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "BMI Class of Children") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))

#MAP 2: BMICLASS2 Geospatial Visualization
DO_1a$SC_AGE_YEARS <- factor(as.integer(DO_1a$SC_AGE_YEARS), levels = c(13,14,15,16,17,18))
DO_1a$SC_HISPANIC_R <- factor(as.integer(DO_1a$SC_HISPANIC_R), levels = c(1,2), labels = c("Hispanic/Latino Origin","Not Hispanic/Latino"))
DO_1a$SC_RACE_R <- factor(as.integer(DO_1a$SC_RACE_R), levels = c(1,2,3,4,5,7), labels = c("White","Black or African American","American Indian or Alaska Native","Asian","Native Hawaiian or Pacific Islander","Two or More Races"))
DO_1a$SC_SEX <- factor(as.integer(DO_1a$SC_SEX), levels = c(1,2), labels = c("Male","Female"))
DO_1a$OVERWEIGHT <- factor(as.integer(DO_1a$OVERWEIGHT), levels = c(1,2), labels = c("Yes","No"))
DO_1a$PHYSACTIV <- factor(as.integer(DO_1a$PHYSACTIV), levels = c(1,2,3,4), labels = c("0 days","1-3 days","4-6 days","Every day"))
DO_1a$SCREENTIME <- factor(as.integer(DO_1a$SCREENTIME), levels = c(1,2,3,4,5), labels = c("<1 hour","1 hour","2 hours","3 hours",">4 hours"))
DO_1a$HOURSLEEP <- factor(as.integer(DO_1a$HOURSLEEP), levels = c(1,2,3,4,5,6,7), labels = c("<6 hours","6 hours","7 hours","8 hours","9 hours","10 hours",">11 hours"))
DO_1a$K2Q32A <- factor(as.integer(DO_1a$K2Q32A), levels = c(1,2), labels = c("Depression","No Depression"))
DO_1a$K2Q33A <- factor(as.integer(DO_1a$K2Q33A), levels = c(1,2), labels = c("Anxiety","No Anxiety"))
newvar <- c()
for (k in 1:19684){
  val <- 0
  if (DO_1a$ACE1[k]==3 | DO_1a$ACE1[k]==4){
    val <- val + 1}
  if (DO_1a$ACE3[k]==1){
    val <- val + 1}
  if (DO_1a$ACE4[k]==1){
    val <- val + 1}
  if (DO_1a$ACE5[k]==1){
    val <- val + 1}
  if (DO_1a$ACE6[k]==1){
    val <- val + 1}
  if (DO_1a$ACE7[k]==1){
    val <- val + 1}
  if (DO_1a$ACE8[k]==1){
    val <- val + 1}
  if (DO_1a$ACE9[k]==1){
    val <- val + 1}
  if (DO_1a$ACE10[k]==1){
    val <- val + 1}
  newvar[k] <- val
}
DO_1a$ACE_Count <- newvar
  
DO_1a$ACE1 <- factor(as.integer(DO_1a$ACE1), levels = c(1,2,3,4), labels = c("No Food Insecurity", "Rare Food Insecurity", "Often Food Insecurity", "Very Often Food Insecurity"))
DO_1a$ACE3 <- factor(as.integer(DO_1a$ACE3), levels = c(1,2), labels = c("Parents Divorced/Separated", "Parents Together"))
DO_1a$ACE4 <- factor(as.integer(DO_1a$ACE4), levels = c(1,2), labels = c("Parent Death", "No Parent Death"))
DO_1a$ACE5 <- factor(as.integer(DO_1a$ACE5), levels = c(1,2), labels = c("Parent Incarcerated", "Parent Not Incarcerated"))
DO_1a$ACE6 <- factor(as.integer(DO_1a$ACE6), levels = c(1,2), labels = c("Witnessed Domestic Violence", "No Domestic Violence"))
DO_1a$ACE7 <- factor(as.integer(DO_1a$ACE7), levels = c(1,2), labels = c("Victim of Violence", "Not Victim of Violence"))
DO_1a$ACE8 <- factor(as.integer(DO_1a$ACE8), levels = c(1,2), labels = c("Lived with Mentally Ill", "No Exposure to Mental Illness"))
DO_1a$ACE9 <- factor(as.integer(DO_1a$ACE9), levels = c(1,2), labels = c("Lived with Alcohol/Drug Abuse", "No Exposure to Alcohol/Drug Abuse"))
DO_1a$ACE10 <- factor(as.integer(DO_1a$ACE10), levels = c(1,2), labels = c("Racism Experienced", "No Racism Experienced"))
colORs <- brewer.pal(2,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = DO_1a, values = "OVERWEIGHT") + scale_fill_manual(values = colORsp(2)) + labs(title = "Overweight Classification of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "Overweight Classification") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))

#MAP 3: RACE Geospatial Visualization
colORs <- brewer.pal(6,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = DO_1a, values = "SC_RACE_R") + scale_fill_manual(values = colORsp(6)) + labs(title = "Racial Categories of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "Racial Category") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))

#MAP 4: PHYSACTIV Geospatial Visualization
colORs <- brewer.pal(4,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = DO_1a, values = "PHYSACTIV") + scale_fill_manual(values = colORsp(4)) + labs(title = "Physical Activity Frequency of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "PA Levels in Children") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))

#MAP 5: ACE AGGREGATE Geospatial Visualization
DO_1a$ACE_Count <- factor(as.integer(DO_1a$ACE_Count), levels = c(0,1,2,3,4,5,6,7,8,9), labels = c("0","1","2","3","4","5","6","7","8","9"))
colORs <- brewer.pal(10,"YlOrRd")
colORsp <- colorRampPalette(colORs)
plot_usmap(data = DO_1a, values = "ACE_Count") + scale_fill_manual(values = colORsp(10)) + labs(title = "ACE Counts of Children aged 13-18") + labs(subtitle = "per U.S. State") + theme(plot.title = element_text(face = "bold")) + theme(plot.title = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(hjust = 0.5)) + theme(plot.subtitle = element_text(face = "bold.italic")) + theme(panel.background = element_rect(color = "black")) + theme(legend.direction = "vertical") + theme(legend.position = "right") + labs(fill = "ACE Count of Children") + theme(legend.key.size = unit(0.7, "cm")) + guides(colour = guide_legend(title.position = "top"))
```